openapi: 3.0.0
# eGSP YAML Template Version: 1.0
# This is a version number for the YAML template. This must not be changed.

info:
  version: 1.0.0
  title: XState-Chatbot
  description: |
    

  contact:
    name: info


paths:

  /message:
    post:
      summary: Receive a message from the user.
      tags: 
        - Chatbot
      parameters:
        - name: ReceiveMessage
          in: header
          schema: 
            $ref: '#/components/schemas/ReceiveMessage'
      responses: 
        '200' :
          description: 'OK'

components:
  schemas:

    ReceiveMessage:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
        user:
          $ref: '#/components/schemas/User'
        extraInfo:
          type: object
          description: Any extra information that might be useful down the line. Primary use case - storing WhatsApp business number (It will useful at the time of sending message to the user. Reply using the same number where the message was received.)
      required:
        - message
        - user
  
    SendMessage:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
        user:
          $ref: '#/components/schemas/User'
        extraInfo:
          type: object
      required: 
        - user
        - message
          
    
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        locale:
          type: string
        userInfo:
          type: object
          description: Any extra specific information provided by user data management service. This is not used by chatbot but could be utilised by further api calls down the line.
      required: 
        - id
    
    Message:
      type: object
      properties:
        type:
          type: string
        input: 
          type: string
      required: 
        - type
        - input
  
    Telemetry:
      type: object
      properties:
        userId:
          type: string
        inputMessage:
          type: object
          properties:
            type:
              type: string
            valid:
              type: boolean
          
    Context:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        slots:
          type: object
          description: Key-Value pair of user's response for a given state of the machine.
