CREATE SEQUENCE SEQ_WS_CON_PB;
CREATE SEQUENCE SEQ_WS_CON_PB_AMRITSAR;
CREATE SEQUENCE SEQ_WS_APP_PB;
CREATE SEQUENCE SEQ_WS_APP_PB_AMRITSAR;
CREATE SEQUENCE SEQ_SW_CON_PB;
CREATE SEQUENCE SEQ_SW_CON_PB_AMRITSAR;
CREATE SEQUENCE SEQ_SW_APP_PB;
CREATE SEQUENCE SEQ_SW_APP_PB_AMRITSAR;
CREATE SEQUENCE SEQ_WS_BILL_RCPT_PB;
CREATE SEQUENCE SEQ_WS_BILL_RCPT_PB_AMRITSAR;
CREATE SEQUENCE SEQ_SW_BILL_RCPT_PB;
CREATE SEQUENCE SEQ_SW_BILL_RCPT_PB_AMRITSAR;
CREATE SEQUENCE SEQ_WS_FEE_RCPT_PB;
CREATE SEQUENCE SEQ_WS_FEE_RCPT_PB_AMRITSAR;
CREATE SEQUENCE SEQ_SW_FEE_RCPT_PB;
CREATE SEQUENCE SEQ_SW_FEE_RCPT_PB_AMRITSAR;







